### ISSUE TITLE
Dataset Format

### ISSUE THREAD

**Issue by SaraGhazanfari** [deepmind/image_obfuscation_benchmark#6]
Hi,
I can't use the dataset in Pytorch. Do you have any plans to share the dataset in another format?
Thanks

**Comment by flostim** [comment]
Hi Sara,

Thanks for your interest! While we don't have evaluation code for Pytorch at the moment you should be able to use TensorFlow Datasets with it: https://www.tensorflow.org/datasets/tfless_tfds#use_with_pytorch

I hope this helps!

Best,
Florian

**Comment by SaraGhazanfari** [comment]
Hi Florian,

Thanks for your quick response! I checked out the link and wrote this code based on that but I get a NoneType error.

```import tensorflow_datasets as tfds
import torch

ds = tfds.load('obfuscated_imagenet', split='validation_PerspectiveTransform',
               data_dir='./dataset')
batch_size = 128
train_loader = torch.utils.data.DataLoader(
    ds,
    sampler=train_sampler,
    batch_size=batch_size,
)

for example in train_loader:
    image, label = example['image'], example['label'] 
```
And here is my detailed error:
```TypeError: 'NoneType' object is not subscriptable```

Could you help me with this?

**Comment by SaraGhazanfari** [comment]
Hi Florian,
Thanks for your response! I could process the data in Pytorch without any further issues.

**Comment by flostim** [comment]
Great to hear! Let me know if you encounter any more problems.
